### ISSUE TITLE
Compatibility Issue with Serverless 2.17.0

### ISSUE THREAD

**Issue by baizhenyu** [rschick/serverless-plugin-lambda-account-access#18]
When I use this plugin, I got some warnings with recent `Serverless` version (2.17.0):

```
Serverless: Configuration warning:
Serverless:   at 'functions.publisherV1': unrecognized property 'allowAccess'
Serverless:   at 'functions.healthcheckV1': unrecognized property 'allowAccess'
Serverless:   at 'provider': unrecognized property 'access'
```
Can anyone fix this please?

**Comment by AntonBazhal** [comment]
Serverless introduced schema validation, so we need to [extend the schema](https://www.serverless.com/framework/docs/providers/aws/guide/plugins/#extending-validation-schema) with our fields.
