### ISSUE TITLE
Not authorized to invoke

### ISSUE THREAD

**Issue by chrille112** [rschick/serverless-plugin-lambda-account-access#6]
On the target function I have added ` serverless-plugin-lambda-account-access` to plugins in serverless.yml, I have added "allowAccounts" with the account id of the calling function and I have added below to the resources (the principal is the account id of the calling function)

      allowAccounts:
        - 415402133663

    resources:
      Resources:
        PermitInvokeFromGroupon:
          Type: AWS::Lambda::Permission
          Properties:
            Action: lambda:InvokeFunction
            FunctionName: "arn:aws:lambda:eu-west-1:xxx:function:integration-prod-getIntegrations"
            Principal: 'xxx'

On the calling function I invoke the function with full arn.
Then I get: `xxx is not authorized to perform: lambda:InvokeFunction on resource xxx`.

Any idea of what I'm missing here?

**Comment by AntonBazhal** [comment]
1. I'm not sure why you need to add custom resource manually. Plugin should do it for you, assuming your principal is `415402133663`
1. You calling function (its role) needs to have permission to invoke target function as well. Like

```json
{
  "Effect": "Allow",
  "Action": [
    "lambda:InvokeFunction"
  ],
  "Resource": "<target function ARN>"
}
```

**Comment by chrille112** [comment]
I have removed the custom resource, I misunderstood the instructions. I already have InvokeFunction for * but I tried adding the full arn without success, I'm still getting the same error.

The function I want to call is in a VPC, can that cause these problems? This is my serverless.yml for the function I want to call:

    service: integration

    plugins:
      - serverless-plugin-typescript
      - serverless-plugin-lambda-account-access

    provider:
      name: aws
      runtime: nodejs6.10
      region: eu-west-1
      environment: ${file(./env.yml):${opt:stage, self:provider.stage}}
      allowAccounts:
        - 415402133663

      iamRoleStatements:
        -  Effect: "Allow"
           Action:
             - "ec2:DescribeInstances"
             - "ec2:CreateNetworkInterface"
             - "ec2:AttachNetworkInterface"
             - "ec2:DetachNetworkInterface"
             - "ec2:DeleteNetworkInterface"
             - "ec2:DescribeNetworkInterfaces"
             - "autoscaling:CompleteLifecycleAction"
           Resource:
             - "*"

    functions:
      getIntegration:
        handler: getIntegration.handler
        timeout: 5
        memorySize: 256
        vpc:
          securityGroupIds:
            - sg-aadc40cc
          subnetIds:
            - subnet-5db9de05
            - subnet-bc7b27ca
            - subnet-60e7bd04


This is the serverless.yml for the calling function:

    service:
      name: market

    plugins:
      - serverless-plugin-typescript

    provider:
      name: aws
      runtime: nodejs6.10
      profile: market
      region: eu-west-1
      environment: ${file(./env.yml):${opt:stage, self:provider.stage}}

      iamRoleStatements:
        - Effect: Allow
          Action:
            - lambda:InvokeFunction
          Resource:
            - "*"

    functions:
      addOrders:
        handler: order.handler
        timeout: 30

**Comment by chrille112** [comment]
I created a non-VPC function and tried to invoke it, but I'm still getting the same error so this isn't related to VPC.

**Comment by chrille112** [comment]
Ah.. should be `allowAccess`, not `allowAccounts`.
